### ISSUE TITLE
Sort policy directives

### ISSUE THREAD

**Issue by eloipeloux** [aeyoll/cspgen-rs#1]
It could be nice to get generated policies sorted alphabetically :)

**Comment by aeyoll** [comment]
Hello @eloipeloux, it should already be the case: https://github.com/aeyoll/cspgen-rs/blob/main/src/csp.rs#L21. Do you have an exemple of unsorted CSPs? Thanks!

**Comment by eloipeloux** [comment]
Hi, in fact the content of one directive is sorted but directives itself aren't !
Sorry for the lack of details in my issue ..!

Here's a sample of what I ended up with using your cspgen command : 

```Content-Security-Policy: base-uri 'self';default-src 'self';script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: ;font-src 'self' data: ;img-src 'self' data: ;style-src 'self' data: 'unsafe-inline' api.mapbox.com;connect-src 'self' api.mapbox.com events.mapbox.com;frame-src 'self' ;```

(that's clearly not an issue, more like a suggestion, 'cause it works like a charm)

Kind regards
